#! /bin/bash

# Ignore errexit with '&& true'
getopt --test >/dev/null && true
if [[ $? -ne 4 ]]; then
  echo 'Sorry,`getopt --test` failed in this environment.'
  exit 1
fi

if ! [ -x "$(command -v ddcutil)" ]; then
  echo 'Sorry `ddcutil` is not installed on the system'
  exit 2
fi

WORKDIR_LOCATION="/tmp/brightnessctl-external"
LAST_BRIGHTNESS="last-brightness"
DEFAULT_BRIGHTNESS=90

detect_monitors() {
  local detectedMonitors=$(
    ddcutil detect |
      grep -E "Display [0-9]+" |
      wc -l
  )
  echo $detectedMonitors
}

LONGOPTS=help,get-brightness,reset
OPTIONS=hgr

PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTS -- "$@") || exit 3
eval set -- "$PARSED"

while true; do
  case "$1" in
  -g | --get-brightness)
    detectedMonitors=$(detect_monitors)
    seq $detectedMonitors |
      xargs -n 1 -P $detectedMonitors \
        sh -c "ddcutil -d \$1 getvcp 10 -t | awk -v monitor=\$1 '{print \"D-\"monitor\" B \"\$4}'" sh
    exit 0
    shift
    ;;
  -r | --reset)
    detectedMonitors=$(detect_monitors)
    seq $detectedMonitors |
      xargs -n 1 -P $detectedMonitors \
        sh -c "(grep D-\$1 $WORKDIR_LOCATION/$LAST_BRIGHTNESS || echo \"D-\$1 B $DEFAULT_BRIGHTNESS\") | awk -v monitor=\$1 '{printf \"ddcutil -d %d setvcp 10 %d\", monitor, \$3}' | sh " sh
    exit 0
    shift
    ;;
  -h | --help)
    printf "External monitor settings helper\n"

    printf "Available options:\n"
    printf "\\t-h, --help\n"
    printf "\\t\\tPrint this help\n"
    printf "\\t-g, --get-brightness\n"
    printf "\\t\\tReturn brightness of all monitors\n"
    printf "\\t[value]\n"
    printf "\\t\\tBrightness value to set - availalbe values between 10-100\n"

    shift
    exit 0
    ;;
  --)
    # Options parameters are parsed and now parsing not found values
    shift

    if ! [[ $1 =~ ^(100|[1-9][0-9])$ ]]; then
      echo "Value invalid - enter value between 10 - 100 (inclusive)"
      exit 5
    fi

    mkdir -p $WORKDIR_LOCATION

    export brightness=$1
    detectedMonitors=$(detect_monitors)

    printf "" >"$WORKDIR_LOCATION/$LAST_BRIGHTNESS"

    # Read current brightness for monitors
    seq $detectedMonitors |
      xargs -n 1 -P $detectedMonitors \
        sh -c "ddcutil -d \$1 getvcp 10 -t | awk -v monitor=\$1 '{print \"D-\"monitor\" B \"\$4}' >> $WORKDIR_LOCATION/$LAST_BRIGHTNESS" sh

    # Set new brightness value
    seq $detectedMonitors |
      xargs -n 1 -P $detectedMonitors sh -c 'ddcutil -d $1 setvcp 10 $brightness' sh

    exit 0
    ;;
  *)
    echo "Programming error"
    exit 4
    ;;
  esac
done
